on:
  pull_request:
    types: [opened]
name: "Hacker Laws Action"

jobs:
  hacker_laws_action:
    runs-on: ubuntu-latest
    name: Hacker Laws Steps
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hacker Laws Action Step
        env:
          PR_URL: ${{ github.event.pull_request.comments_url }}
          PR_SENDER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: umutphp/hacker-laws-action@v1
        id: hacker_laws_action

