name: Markdown Linter

on:
  [push, pull_request]

jobs:
  hacker_laws_action:
    runs-on: ubuntu-latest
    name: Markdown Linter Steps
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Markdown Linter"
        uses: nosborn/github-action-markdown-cli@v3.1.0
        with:
          files: .
          ignore_files: "LICENSE"
